### PR TITLE
Group JavaScript capstone project 

### PR DESCRIPTION
**Pull request by EddyShimwa**
### Generall requirements
- Followed medium-fidelity wireframes to create a UI.
- Used GitFlow to work with other developers in a team.
- Use JavaScript to make websites dynamic and build basic single-page apps.
- Use AAA pattern for unit tests.
- Followed Gitflow.
- Send and receive data from an API.
- Perform a code review for a team member.
- Project requirements
- Loaded data from [Meals DB](https://www.themealdb.com/api.php).

- Used [Involvement API](https://www.notion.so/microverse/Involvement-API-869e60b5ad104603aa6db59e08150270) to record the different user interactions (likes, comments).

### Interfaces

- The home page.
- The comments popup.
- Home page
- When the page loads, the webapp retrieves data from:
- The selected API and shows the list of items on screen.
- The Involvement API to show the item likes.

- When the user clicks on the Like button of an item, the interaction is recorded in the Involvement API and the screen is updated.
- When the user clicks on the "Comments" button, the Comments popup appears.

### Comments popup
- When the popup loads, the webapp retrieves data from:
- The selected API and shows details about the selected item.
- The Involvement API to show the item comments.
- When the user clicks on the "Comment" button, the data is recorded in the Involvement API and the screen is updated.

### Counters We have counters in all the interfaces that show:

- The number of items (home).
- The number of comments (comments popup).

### CODE REVIEW

**Review by AnselemOdims — APPROVED** [review]
### Hi  @team 🙋‍♀️, 
Good job implementing all the project requirements for this milestone/project.

# STATUS APPROVED ✔
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Use the tag @AnselemOdims for a quicker reply


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by EddyShimwa** [comment]
@AnselemOdims  Thanks a Lot!

**Comment by gitbygaurav** [comment]
Hii @AnselemOdims 

Thanks for your review 😊

**Comment by gitbygaurav** [comment]
Hi, @EddyShimwa I just wanted to take a moment to express my sincerest gratitude for your hard work and dedication on this project. Your expertise in coding has been invaluable, and I have learned so much from working alongside you. I truly appreciate your willingness to collaborate, share your knowledge, and offer support whenever I needed it. Your contributions have been essential to the success of this project, and I am grateful to have had the opportunity to work with you. Thank you for all of your hard work and for being an amazing coding partner. I am looking forward to continuing our partnership on future projects.

Once again thanks a lot 😊.

**Pull request merged**
